{
 "title": "HIDS - Network Attack Monitoring",
 "tags": [
  "security",
  "network",
  "attacks",
  "hids"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_POSTGRES", "label": "PostgreSQL Datasource", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Total Attacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Total Attacks\"\nFROM attack_logs\nWHERE $__timeFilter(event_time)"
    }
   ]
  },
  {
   "title": "Attackers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT src_addr) AS \"Unique IP\"\nFROM attack_logs\nWHERE $__timeFilter(event_time)"
    }
   ]
  },
  {
   "title": "Blocked Attacks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Blocked\"\nFROM attack_logs\nWHERE $__timeFilter(event_time)\n  AND response_type = 'Block'"
    }
   ]
  },
  {
   "title": "Total Attack",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 13, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "postgres",
     "rawSql": "SELECT\n  attack_type AS metric,\n  COUNT(*) AS value\nFROM attack_logs\nWHERE $__timeFilter(event_time)\nGROUP BY attack_type\nORDER BY value DESC;"
    }
   ]
  },
  {
   "title": "All Unique IPs - Attack Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT \n  src_addr AS \"IP Address\",\n  COUNT(*) AS \"Total Attacks\"\nFROM attack_logs \nWHERE $__timeFilter(event_time)\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "All Attack Types - Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT \n  attack_type AS \"Attack Type\",\n  COUNT(*) AS \"Count\"\nFROM attack_logs \nWHERE $__timeFilter(event_time)\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Recent Attack Events",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n  event_time AS \"Time\", \n  src_addr AS \"Source\", \n  dst_addr AS \"Destination\", \n  dst_port AS \"Port\", \n  attack_type AS \"Type\", \n  attack_detail AS \"Detail\", \n  response_type AS \"Action\" \nFROM attack_logs \nWHERE $__timeFilter(event_time)\nORDER BY event_time ASC"
    }
   ]
  }
 ]
}