# --- Prevention Mode---
# 0 = Disabled
# 1 = Enabled
PREVENTION_MODE=0

# --- Memory Cleanup Timeouts (Seconds) ---
# Clean old state connection
IP_TIMEOUT=2
SSH_TIMEOUT=30
FTP_TIMEOUT=30
HTTP_TIMEOUT=2
IP_PORT_CONNECT_TIMEOUT=30
UDP_PORT_CONNECT_TIMEOUT=2
ICMP_CONNECT_TIMEOUT=2

# --- Punishment (Minutes) ---
# Duration to block an IP address when an attack is detected.
# Unit: Minutes (e.g., 1 = 1 minute, 60 = 1 hour).
BLOCK_TIMEOUT=60

# --- ICMP Flood (Ping Flood) ---
# 500 ICMP packets per second is considered a flood attack.
ICMP_PPS_LIMIT=500

# --- Port Scan Detection ---
# More than 80 connection attempts within 30 seconds is considered a port scan.
PORT_CONNECT_LIMIT=80
PORT_CONNECT_DURATION_LIMIT=30

# --- SYN Flood (DoS) ---
# More than 500 SYN packets per second is considered a SYN Flood attack.
SYN_PPS_LIMIT=500

# --- UDP Flood (DoS) ---
# More than 500 UDP packets per second is considered a UDP Flood attack.
UDP_PPS_LIMIT=500

# (Deprecated / Unused)
# Number of unreachable ports before triggering detection.
UNREACH_COUNT_LIMIT=30

# --- SSH Brute Force ---
# More than 10 failed login attempts within 10 seconds is considered a brute-force attack.
SSH_LOGIN_FAIL_LIMIT=10
SSH_LOGIN_FAIL_DURATION_LIMIT=10
SSH_DURATION_LIMIT=60

# --- FTP Brute Force ---
# More than 10 failed login attempts within 10 seconds is considered a brute-force attack.
FTP_LOGIN_FAIL_LIMIT=10
FTP_LOGIN_FAIL_DURATION_LIMIT=10
FTP_DURATION_LIMIT=60

# BTMP: Logs failed login attempts (binary file).
BTMP_PATH=/var/log/btmp

# VSFTPD: Logs for the VSFTPD service.
VSFTPD_LOG_PATH=/var/log/vsftpd.log

# --- HTTP Byte Response Length ---
# Minimum HTTP response size used for analysis.
HTTP_BYTE_LEN_LIMIT=100

# --- Postgres ---
